<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../XIVChatCommon/XIVChatCommon.csproj" />
    <ProjectReference Include="../../XIVChatStorage/XIVChatStorage.csproj" />
    <Compile Include="../../XIVChat Desktop/ConfigurationFile.cs" Link="ConfigurationFile.cs" />
    <Compile Include="../../XIVChatPlugin/Client.cs" Link="Client.cs" />
    <Compile Include="../../XIVChatPlugin/FriendListCoordinator.cs" Link="FriendListCoordinator.cs" />
    <Compile Include="../../XIVChat Desktop/FriendListSession.cs" Link="FriendListSession.cs" />
  </ItemGroup>
</Project>
